version: '3.8'

services:
  app:
    container_name: class-tracker-server
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env